rt_bi_emulator:
  av1:
    ros__parameters:
      render: True
      id: "https://rezateshnizi.com/tower_bridge/defintion/av1"
      updateInterval: 0.75
      timesSecs:
        - 0.0
        - 50.0
      cutOffTime: inf
      centersOfRotation:
        - "[120.804, 134.190]"
        - "[120.804, 134.190]"
      polygons:
        - "[[283.602, 65.354], [296.297, 119.257], [120.804, 134.190]]"
        - "[[200.612, -24.140], [244.985, 8.992], [120.804, 134.190]]"
  av2:
    ros__parameters:
      render: True
      id: "https://rezateshnizi.com/tower_bridge/defintion/av2"
      updateInterval: 0.75
      timesSecs:
        - 0.0
        - 50.0
      cutOffTime: inf
      centersOfRotation:
        - "[342.837, -48.842]"
        - "[342.837, -48.842]"
      polygons:
        - "[[180.038, 19.995], [167.343, -33.908], [342.837, -48.842]]"
        - "[[263.028, 109.489], [218.655, 76.357], [343.492, -47.888]]"
