rt_bi_emulator:
  em_kn1:
    ros__parameters:
      render: True
      id: "1"
      updateInterval: 0.25
      timesSecs:
        - 0.0
        - 50.0
      cutOffTime: inf
      saPoses:
        - "[490.0, 30.0, 0.0]"
        - "[10.0, 70.0, 0.0]"
      centersOfRotation:
        - "[490.0, 30.0]"
        - "[10.0, 70.0]"
      fovs:
        - "[[485.0, 25.0], [495.0, 25.0], [495.0, 35.0], [485.0, 35.0]]"
        - "[[15.0, 65.0], [25.0, 65.0], [25.0, 85.0], [15.0, 85.0]]"
