rt_bi_emulator:
  kn1:
    ros__parameters:
      render: True
      id: "https://rezateshnizi.com/rt-bi/tower_bridge/defintion/kn1"
      updateInterval: 0.25
      timesSecs:
        - 0.0
        - 50.0
      cutOffTime: inf
      saPoses:
        - "[490.0, 30.0, 0.0]"
        - "[10.0, 70.0, 0.0]"
      centersOfRotation:
        - "[490.0, 30.0]"
        - "[10.0, 70.0]"
      fovs:
        - "[[485.0, 25.0], [495.0, 25.0], [495.0, 35.0], [485.0, 35.0]]"
        - "[[15.0, 65.0], [25.0, 65.0], [25.0, 85.0], [15.0, 85.0]]"

  king:
    ros__parameters:
      render: True
      id: "https://rezateshnizi.com/rt-bi/tower_bridge/defintion/king"
      updateInterval: 0.25
      timesSecs:
        - 0.00
        - 10.00
        - 16.00
        - 50.00
      cutOffTime: inf
      saPoses:
        - "[150.0, 105.0, 0.0]"
        - "[250.0, 105.0, 0.0]"
        - "[250.0, 15.0, 0.0]"
        - "[490.0, 15.0, 0.0]"
      centersOfRotation:
        - "[150.0, 105.0]"
        - "[250.0, 105.0]"
        - "[250.0, 15.0]"
        - "[490.0, 15.0]"
      fovs:
        - "[[145.0, 100.0], [155.0, 100.0], [155.0, 110.0], [145.0, 110.0]]"
        - "[[225.0, 102.0], [235.0, 102.0], [235.0, 112.0], [225.0, 112.0]]"
        - "[[255.0, 10.0], [265.0, 10.0], [265.0, 20.0], [255.0, 20.0]]"
        - "[[485.0, 8.0], [495.0, 8.0], [495.0, 18.0], [485.0, 18.0]]"
