rt_bi_emulator:
  gv1:
    ros__parameters:
      trajectory_id: 1
      detection_label: car
      timeSecs:
        - 0.0
        - 2.0
        - 4.0
        - 6.0
        - 8.0
        - 10.0
        - 12.0
        - 14.0
        - 16.0
        - 18.0
        - 20.0
        - 22.0
        - 24.0
        - 26.0
        - 28.0
        - 30.0
        - 32.0
        - 34.0
        - 36.0
        - 38.0
        - 40.0
        - 42.0
        - 44.0
        - 46.0
      saPoses:
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
      velocity:
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
  gv2:
    ros__parameters:
      trajectory_id: 2
      detection_label: tank
      timeSecs:
        - 0.0
        - 2.0
        - 4.0
        - 6.0
        - 8.0
        - 10.0
        - 12.0
        - 14.0
        - 16.0
        - 18.0
        - 20.0
        - 22.0
        - 24.0
        - 26.0
        - 28.0
        - 30.0
        - 32.0
        - 34.0
        - 36.0
        - 38.0
        - 40.0
        - 42.0
        - 44.0
        - 46.0
      saPoses:
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
      velocity:
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[0.0, 10.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
        - "[10.0, 15.0, 0.0]"
