rt_bi_emulator:
  tg1:
    ros__parameters:
      render: False
      id: "https://rezateshnizi.com/rt-bi/tower_bridge/defintion/tg1"
      updateInterval: 0.25
      timesSecs:
        - 0.0
        - 50.0
      cutOffTime: inf
      centersOfRotation:
        - "[15.0, 15.0]"
        - "[490.0, 15.0]"
      polygons:
        - "[[10.0, 10.0], [20.0, 10.0], [20.0, 20.0], [10.0, 20.0]]"
        - "[[485.0, 10.0], [495.0, 10.0], [495.0, 20.0], [485.0, 20.0]]"
