rt_bi_emulator:
  tg1:
    ros__parameters:
      render: False
      id: "https://rezateshnizi.com/rt-bi/tower_bridge/defintion/tg1"
      updateInterval: 0.25
      timesSecs:
        - 0.0
        - 60.0
      cutOffTime: inf
      centersOfRotation:
        - "[15.0, 28.0]"
        - "[490.0, 28.0]"
      polygons:
        - "[[12.0, 25.0], [21.0, 25.0], [21.0, 31.0], [12.0, 31.0]]"
        - "[[485.0, 25.0], [495.0, 25.0], [495.0, 31.0], [485.0, 31.0]]"
