PREFIX dc:             <http://purl.org/dc/elements/1.1/>
PREFIX interval:       <https://rezateshnizi.com/rt-bi/tower_bridge/temporal/intervals#>
PREFIX owl:            <http://www.w3.org/2002/07/owl#>
PREFIX polygon:        <https://rezateshnizi.com/rt-bi/tower_bridge/spatial/polygons#>
PREFIX pt:             <https://rezateshnizi.com/rt-bi/tower_bridge/spatial/pts#>
PREFIX rdf:            <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:           <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rt_bi:          <https://rezateshnizi.com/rt-bi/>
PREFIX spatial_props:  <https://rezateshnizi.com/rt-bi/spatial/props#>
PREFIX t:              <https://rezateshnizi.com/rt-bi/tower_bridge/temporal/ts#>
PREFIX temporal_props: <https://rezateshnizi.com/rt-bi/temporal/props#>
PREFIX tower_bridge:   <https://rezateshnizi.com/rt-bi/tower_bridge/>
PREFIX traversability: <https://rezateshnizi.com/rt-bi/tower_bridge/traversability#>
PREFIX world_props:    <https://rezateshnizi.com/rt-bi/world/props#>
PREFIX x:              <https://rezateshnizi.com/rt-bi/tower_bridge/spatial/xs#>
PREFIX xsd:            <http://www.w3.org/2001/XMLSchema#>
PREFIX y:              <https://rezateshnizi.com/rt-bi/tower_bridge/spatial/ys#>

SELECT
	?regularSetId ?setType
	# SELECTED VARIABLES ########################
WHERE {
	VALUES ?regularSetId {
		# ID VALUES #############################
	}
	?regularSetId a ?setType.
	# SELECTOR ##################################
}
ORDER BY ?regularSetId # ORDER VARIABLES ###########################
