PREFIX dc:             <http://purl.org/dc/elements/1.1/>
PREFIX interval:       <https://rezateshnizi.com/tower_bridge/temporal/intervals#>
PREFIX owl:            <http://www.w3.org/2002/07/owl#>
PREFIX polygon:        <https://rezateshnizi.com/tower_bridge/spatial/polygons#>
PREFIX pt:             <https://rezateshnizi.com/tower_bridge/spatial/pts#>
PREFIX rdf:            <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:           <http://www.w3.org/2000/01/rdf-schema#>
PREFIX class:          <https://rezateshnizi.com/rt-bi/class#>
PREFIX spatial:  <https://rezateshnizi.com/rt-bi/spatial#>
PREFIX t:              <https://rezateshnizi.com/tower_bridge/temporal/ts#>
PREFIX temporal: <https://rezateshnizi.com/rt-bi/temporal#>
PREFIX tower_bridge:   <https://rezateshnizi.com/tower_bridge/>
PREFIX material: <https://rezateshnizi.com/tower_bridge/materials#>
PREFIX subject:    <https://rezateshnizi.com/rt-bi/subject#>
PREFIX x:              <https://rezateshnizi.com/tower_bridge/spatial/xs#>
PREFIX xsd:            <http://www.w3.org/2001/XMLSchema#>
PREFIX y:              <https://rezateshnizi.com/tower_bridge/spatial/ys#>

SELECT
	?regularSetId ?setType
	# SELECTED VARIABLES ########################
WHERE {
	?regularSetId a/rdfs:subClassOf* ?namespace .
	?regularSetId a ?setType.
	# SELECTOR ##################################
	# BIND ######################################
}
ORDER BY ?regularSetId # ORDER VARIABLES ###########################
