rt_bi_runtime:
  ba1:
    ros__parameters:
      render: True
      states:
        - "Q0"
        - "Q1"
        - "Q2"
        - "Q3"
      transitions:
        - "[[\"south bank\", \"Q1\"]]"
        - "[[\"mid-day\", \"Q2\"]]"
        - "[[\"north shore\", \"Q3\"]]"
        - "[]"
      start: "Q0"
      accepting:
        - "Q3"
