rt_bi_runtime:
  dd_spatial1:
    ros__parameters:
      param_src: "{'pts': 'rt_bi_runtime/dd_coords1/xs, rt_bi_runtime/dd_coords1/ys', 'polygons': 'rt_bi_runtime/dd_spatial1/pts'}"
      pts:
        - "[0, 0]"
        - "[0, 1]"
        - "[0, 2]"
        - "[0, 3]"
        - "[1, 2]"
        - "[1, 3]"
        - "[2, 2]"
        - "[2, 3]"
        - "[3, 0]"
        - "[3, 1]"
        - "[3, 2]"
        - "[3, 3]"
        - "[4, 0]"
        - "[4, 1]"
        - "[4, 2]"
        - "[4, 3]"
        - "[5, 0]"
        - "[5, 1]"
        - "[5, 2]"
        - "[5, 3]"
      polygons:
        - "[0, 8, 12, 16, 17, 13, 9, 1]"
        - "[1, 9, 10, 6, 4, 2]"
        - "[2, 4, 5, 3]"
        - "[4, 6, 7, 5]"
        - "[6, 10, 14, 18, 19, 15, 11]"
        - "[9, 13, 14, 10]"
        - "[13, 17, 18, 14]"
