rt_bi_runtime:
  dd_coords1:
    ros__parameters:
      xs:
        - 0.0
        - 120.0
        - 140.0
        - 200.0
        - 400.0
        - 600.0
      ys:
        - 0.0
        - 30.0
        - 90.0
        - 120.0
