rt_bi_runtime:
  runtime_mgr:
    ros__parameters:
      render: False
      await_cold_start:
        - "/rt_bi_runtime/ba1"
        - "/rt_bi_emulator/emulator_dynamic_map"
  ba1:
    ros__parameters:
      render: True
      grammar_dir: "rdf"
      grammar_file: "transition.lark"
      states:
        - "Q0"
        - "Q1"
        - "Q2"
        - "Q3"
      transitions_from:
        - "Q0"
        - "Q1"
        - "Q2"
      transitions_predicate:
        - 'S[name == "south-bank"] AND S[traversability.legs == true]'
        - 'T[name == "mid-day"]'
        - 'S[name == "north-shore"] AND S[traversability.legs == true]'
      transitions_to:
        - "Q1"
        - "Q2"
        - "Q3"
      start: "Q0"
      accepting:
        - "Q3"
