rt_bi_runtime:
  runtime_mgr:
    ros__parameters:
      render: False
      await_cold_start:
        - "/rt_bi_emulator/em_dynamic_map"
        - "/rt_bi_runtime/ba1"
  ba1:
    ros__parameters:
      render: True
      states:
        - "Q0"
        - "Q1"
        - "Q2"
        - "Q3"
      transitions:
        - '[["Transitions.SouthBank()", "Q1"]]'
        - '[["Transitions.MidDay()", "Q2"]]'
        - '[["Transitions.NorthShore()", "Q3"]]'
        - '[]'
      start: "Q0"
      accepting:
        - "Q3"
