rt_bi_runtime:
  dd:
    ros__parameters:
      alphabet:
        - "LEFT"
        - "RIGHT"
        - "NOON"
      types:
        - "S"
        - "S"
        - "T"
      descriptions:
        - "[[15.0, 25.0], [15.0, 75.0], [115.0, 75.0], [115.0, 25.0]]"
        - "[[385.0, 25.0], [385.0, 75.0], [485.0, 75.0], [485.0, 25.0]]"
        - "[[24.5, 25.5]]"
