- 
  name:             uav1
  type:             uav
  domain_id:        1
  update_frequency: 100.0
  v_max: 8.0
  sim_start:
    x: -120.0
    y: -6.0
    yaw:  0.0
  sensor:
    type: camera
    detection_frequency: 10.0
    alpha: 0.1
    r0: 3.0
    fov:
      x: [10.0, 10.0, -10.0, -10.0]
      y: [10.0, -10.0, -10.0, 10.0]
      width: 20
      height: 20
-
  name:             beam_static
  type:             static
  domain_id:        2
  update_frequency: 100.0
  sim_start:
    x: 0.0
    y: 0.0
    yaw:  0.0
  sensor:
    type: beam
    detection_frequency: 10.0
    alpha: 0.1
    r0: 3.0
    fov:
      x: [10.0, 10.0]
      y: [10.0, -10.0]
-
  name:             camera_static
  domain_id:        3
  type:             static
  update_frequency: 100.0
  sim_start:
    x: 105.0
    y: -20.0
    yaw:  0.0
  sensor:
    type: camera
    detection_frequency: 10.0
    alpha: 0.1
    r0: 3.0
    fov:
      x: [10.0, 10.0, -10.0, -10.0]
      y: [10.0, -10.0, -10.0, 10.0]
      width: 20
      height: 20
